## Preprocess

In [1]:
import pandas as pd
import numpy as np
import importlib as imp
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
import sys

sys.path.insert(0,'..\src')

In [2]:
try:
    imp.reload(sys.modules['preprocess'])
except KeyError:
    pass

from preprocess import BasePreprocess

In [3]:
try:
    imp.reload(sys.modules['Scoring'])
except KeyError:
    pass

from Scoring import Scoring
s = Scoring()

In [4]:
data1 = BasePreprocess(pd.read_csv('../data/cars.csv')).run(ohIncludeBool = True, toDrop = ['manufacturer_name', 'model_name', 'number_of_photos', 'color', 'up_counter'])
data2 = BasePreprocess(pd.read_csv('../data/lab2/diabetes_012_health_indicators_BRFSS2015.csv')).run()

Found gaps in 1 columns
Found 7 categorial signs (meaning object types)
Found 13 categorial signs (meaning bool types)
Found gaps in 0 columns
Found 0 categorial signs (meaning object types)


In [5]:
data1

odometer_value  year_produced  engine_capacity  price_usd  \
0              190000           2010              2.5   10900.00   
1              290000           2002              3.0    5000.00   
2              402000           2001              2.5    2800.00   
3               10000           1999              3.0    9999.00   
4              280000           2001              2.5    2134.11   
...               ...            ...              ...        ...   
38526          290000           2000              3.5    2750.00   
38527          321000           2004              2.2    4800.00   
38528          777957           2000              3.5    4300.00   
38529           20000           2001              2.0    4000.00   
38530          297729           2000              2.4    3200.00   

       duration_listed  transmission_mechanical  engine_fuel_electric  \
0                   16                        0                     0   
1                   83                        0                     0   
2                  151                        0                     0   
3                   86                        1                     0   
4                    7                        0                     0   
...                ...                      ...                   ...   
38526              301                        0                     0   
38527              317                        1                     0   
38528              369                        0                     0   
38529              490                        1                     0   
38530              632                        0                     0   

       engine_fuel_gas  engine_fuel_gasoline  engine_fuel_hybrid-diesel  ...  \
0                    0                     1                          0  ...   
1                    0                     1                          0  ...   
2                    0                     1                          0  ...   
3                    0                     1                          0  ...   
4                    0                     1                          0  ...   
...                ...                   ...                        ...  ...   
38526                0                     1                          0  ...   
38527                0                     0                          0  ...   
38528                0                     1                          0  ...   
38529                0                     1                          0  ...   
38530                0                     1                          0  ...   

       feature_0_True  feature_1_True  feature_2_True  feature_3_True  \
0                   0               1               1               1   
1                   0               1               0               0   
2                   0               1               0               0   
3                   1               0               0               0   
4                   0               1               0               1   
...               ...             ...             ...             ...   
38526               0               1               0               0   
38527               0               1               0               0   
38528               0               1               0               0   
38529               0               1               0               0   
38530               0               0               0               0   

       feature_4_True  feature_5_True  feature_6_True  feature_7_True  \
0                   0               1               0               1   
1                   1               1               0               0   
2                   0               0               0               0   
3                   0               0               0               0   
4                   1               0               0               0   
...               ...             ...

In [6]:
data2

Diabetes_012  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0                0.0     1.0       1.0        1.0  40.0     1.0     0.0   
1                0.0     0.0       0.0        0.0  25.0     1.0     0.0   
2                0.0     1.0       1.0        1.0  28.0     0.0     0.0   
3                0.0     1.0       0.0        1.0  27.0     0.0     0.0   
4                0.0     1.0       1.0        1.0  24.0     0.0     0.0   
...              ...     ...       ...        ...   ...     ...     ...   
253675           0.0     1.0       1.0        1.0  45.0     0.0     0.0   
253676           2.0     1.0       1.0        1.0  18.0     0.0     0.0   
253677           0.0     0.0       0.0        1.0  28.0     0.0     0.0   
253678           0.0     1.0       0.0        1.0  23.0     0.0     0.0   
253679           2.0     1.0       1.0        1.0  25.0     0.0     0.0   

        HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
0                        0.0           0.0     0.0  ...            1.0   
1                        0.0           1.0     0.0  ...            0.0   
2                        0.0           0.0     1.0  ...            1.0   
3                        0.0           1.0     1.0  ...            1.0   
4                        0.0           1.0     1.0  ...            1.0   
...                      ...           ...     ...  ...            ...   
253675                   0.0           0.0     1.0  ...            1.0   
253676                   0.0           0.0     0.0  ...            1.0   
253677                   0.0           1.0     1.0  ...            1.0   
253678                   0.0           0.0     1.0  ...            1.0   
253679                   1.0           1.0     1.0  ...            1.0   

        NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  \
0               0.0      5.0      18.0      15.0       1.0  0.0   9.0   
1               1.0      3.0       0.0       0.0       0.0  0.0   7.0   
2               1.0      5.0      30.0      30.0       1.0  0.0   9.0   
3               0.0      2.0       0.0       0.0       0.0  0.0  11.0   
4               0.0      2.0       3.0       0.0       0.0  0.0  11.0   
...             ...      ...       ...       ...       ...  ...   ...   
253675          0.0      3.0       0.0       5.0       0.0  1.0   5.0   
253676          0.0      4.0       0.0       0.0       1.0  0.0  11.0   
253677          0.0      1.0       0.0       0.0       0.0  0.0   2.0   
253678          0.0      3.0       0.0       0.0       0.0  1.0   7.0   
253679          0.0      2.0       0.0       0.0       0.0  0.0   9.0   

        Education  Income  
0             4.0     3.0  
1             6.0     1.0  
2             4.0     8.0  
3             3.0     6.0  
4             5.0     4.0  
...           ...     ...  
253675        6.0     7.0  
253676        2.0     4.0  
253677        5.0     2.0  
253678        5.0     1.0  
253679        6.0     2.0  

[253680 rows x 22 columns]

In [7]:
y1 = data1['price_usd']
X1 = data1.drop(['price_usd'], axis=1)

In [8]:
y1

0        10900.00
1         5000.00
2         2800.00
3         9999.00
4         2134.11
           ...   
38526     2750.00
38527     4800.00
38528     4300.00
38529     4000.00
38530     3200.00
Name: price_usd, Length: 38531, dtype: float64

In [9]:
X1

odometer_value  year_produced  engine_capacity  duration_listed  \
0              190000           2010              2.5               16   
1              290000           2002              3.0               83   
2              402000           2001              2.5              151   
3               10000           1999              3.0               86   
4              280000           2001              2.5                7   
...               ...            ...              ...              ...   
38526          290000           2000              3.5              301   
38527          321000           2004              2.2              317   
38528          777957           2000              3.5              369   
38529           20000           2001              2.0              490   
38530          297729           2000              2.4              632   

       transmission_mechanical  engine_fuel_electric  engine_fuel_gas  \
0                            0                     0                0   
1                            0                     0                0   
2                            0                     0                0   
3                            1                     0                0   
4                            0                     0                0   
...                        ...                   ...              ...   
38526                        0                     0                0   
38527                        1                     0                0   
38528                        0                     0                0   
38529                        1                     0                0   
38530                        0                     0                0   

       engine_fuel_gasoline  engine_fuel_hybrid-diesel  \
0                         1                          0   
1                         1                          0   
2                         1                          0   
3                         1                          0   
4                         1                          0   
...                     ...                        ...   
38526                     1                          0   
38527                     0                          0   
38528                     1                          0   
38529                     1                          0   
38530                     1                          0   

       engine_fuel_hybrid-petrol  ...  feature_0_True  feature_1_True  \
0                              0  ...               0               1   
1                              0  ...               0               1   
2                              0  ...               0               1   
3                              0  ...               1               0   
4                              0  ...               0               1   
...                          ...  ...             ...             ...   
38526                          0  ...               0               1   
38527                          0  ...               0               1   
38528                          0  ...               0               1   
38529                          0  ...               0               1   
38530                          0  ...               0               0   

       feature_2_True  feature_3_True  feature_4_True  feature_5_True  \
0                   1               1               0               1   
1                   0               0               1               1   
2                   0               0               0               0   
3                   0               0               0               0   
4                   0               1               1               0   
...               ...             ...             ...             ...   
38526               0               0               1               1   
38527               0               0               1               1   
38528     

In [10]:
from sklearn.model_selection import train_test_split
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.2, random_state=38)

In [11]:
X1_train.shape, X1_test.shape, y1_train.shape, y1_test.shape

((30824, 45), (7707, 45), (30824,), (7707,))

In [12]:
y2 = data2['Diabetes_012']
X2 = data2.drop(['Diabetes_012'], axis=1)

In [13]:
y2

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
         ... 
253675    0.0
253676    2.0
253677    0.0
253678    0.0
253679    2.0
Name: Diabetes_012, Length: 253680, dtype: float64

In [14]:
X2

HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0          1.0       1.0        1.0  40.0     1.0     0.0   
1          0.0       0.0        0.0  25.0     1.0     0.0   
2          1.0       1.0        1.0  28.0     0.0     0.0   
3          1.0       0.0        1.0  27.0     0.0     0.0   
4          1.0       1.0        1.0  24.0     0.0     0.0   
...        ...       ...        ...   ...     ...     ...   
253675     1.0       1.0        1.0  45.0     0.0     0.0   
253676     1.0       1.0        1.0  18.0     0.0     0.0   
253677     0.0       0.0        1.0  28.0     0.0     0.0   
253678     1.0       0.0        1.0  23.0     0.0     0.0   
253679     1.0       1.0        1.0  25.0     0.0     0.0   

        HeartDiseaseorAttack  PhysActivity  Fruits  Veggies  ...  \
0                        0.0           0.0     0.0      1.0  ...   
1                        0.0           1.0     0.0      0.0  ...   
2                        0.0           0.0     1.0      0.0  ...   
3                        0.0           1.0     1.0      1.0  ...   
4                        0.0           1.0     1.0      1.0  ...   
...                      ...           ...     ...      ...  ...   
253675                   0.0           0.0     1.0      1.0  ...   
253676                   0.0           0.0     0.0      0.0  ...   
253677                   0.0           1.0     1.0      0.0  ...   
253678                   0.0           0.0     1.0      1.0  ...   
253679                   1.0           1.0     1.0      0.0  ...   

        AnyHealthcare  NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  \
0                 1.0          0.0      5.0      18.0      15.0       1.0   
1                 0.0          1.0      3.0       0.0       0.0       0.0   
2                 1.0          1.0      5.0      30.0      30.0       1.0   
3                 1.0          0.0      2.0       0.0       0.0       0.0   
4                 1.0          0.0      2.0       3.0       0.0       0.0   
...               ...          ...      ...       ...       ...       ...   
253675            1.0          0.0      3.0       0.0       5.0       0.0   
253676            1.0          0.0      4.0       0.0       0.0       1.0   
253677            1.0          0.0      1.0       0.0       0.0       0.0   
253678            1.0          0.0      3.0       0.0       0.0       0.0   
253679            1.0          0.0      2.0       0.0       0.0       0.0   

        Sex   Age  Education  Income  
0       0.0   9.0        4.0     3.0  
1       0.0   7.0        6.0     1.0  
2       0.0   9.0        4.0     8.0  
3       0.0  11.0        3.0     6.0  
4       0.0  11.0        5.0     4.0  
...     ...   ...        ...     ...  
253675  1.0   5.0        6.0     7.0  
253676  0.0  11.0        2.0     4.0  
253677  0.0   2.0        5.0     2.0  
253678  1.0   7.0        5.0     1.0  
253679  0.0   9.0        6.0     2.0  

[253680 rows x 21 columns]

In [15]:
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, test_size=0.33, random_state=38)

In [16]:
X2_train.shape, X2_test.shape, y2_train.shape, y2_test.shape

((169965, 21), (83715, 21), (169965,), (83715,))

In [17]:
from preprocess import Sampling

X_train_ros, y_train_ros = Sampling.sample(X = X2_train, y = y2_train, usingMethod = 'RandomlyOverSample')
X_train_rus, y_train_rus = Sampling.sample(X = X2_train, y = y2_train, usingMethod = 'RandomlyUnderSample')

[(0.0, 143231), (1.0, 143231), (2.0, 143231)]
[(0.0, 3096), (1.0, 3096), (2.0, 3096)]


# Задание 1

In [35]:
import tensorflow as tf

## Регрессия

In [37]:
model_regression = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(64, activation="relu", input_shape=(45,)),
        tf.keras.layers.Dense(32, activation="sigmoid"),
        tf.keras.layers.Dropout(0.1),
        tf.keras.layers.Dense(16, activation="relu"),
        tf.keras.layers.Dropout(0.1),
        tf.keras.layers.Dense(1, activation="linear"),
    ]
)

In [38]:
model_regression.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 64)                2944      
                                                                 
 dense_5 (Dense)             (None, 32)                2080      
                                                                 
 dropout_2 (Dropout)         (None, 32)                0         
                                                                 
 dense_6 (Dense)             (None, 16)                528       
                                                                 
 dropout_3 (Dropout)         (None, 16)                0         
                                                                 
 dense_7 (Dense)             (None, 1)                 17        
                                                                 
Total params: 5,569
Trainable params: 5,569
Non-traina

In [39]:
model_regression.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.005), loss="mse")

In [40]:
model_regression.fit(X1_train, y1_train, epochs=50)

Epoch 1/50
964/964 [==============================] - 8s 5ms/step - loss: 61097280.0000
Epoch 2/50
964/964 [==============================] - 5s 5ms/step - loss: 42164160.0000
Epoch 3/50
964/964 [==============================] - 4s 5ms/step - loss: 42099784.0000
Epoch 4/50
964/964 [==============================] - 5s 5ms/step - loss: 42018980.0000
Epoch 5/50
964/964 [==============================] - 5s 5ms/step - loss: 42066588.0000
Epoch 6/50
964/964 [==============================] - 5s 5ms/step - loss: 42188224.0000
Epoch 7/50
964/964 [==============================] - 5s 5ms/step - loss: 42041300.0000
Epoch 8/50
964/964 [==============================] - 4s 5ms/step - loss: 42007596.0000
Epoch 9/50
964/964 [==============================] - 5s 5ms/step - loss: 42042368.0000
Epoch 10/50
964/964 [==============================] - 5s 5ms/step - loss: 42112264.0000
Epoch 11/50
964/964 [==============================] - 5s 5ms/step - loss: 42034024.0000
Epoch 12/50
964/964 [=========

In [41]:
reg_neuro_pred = model_regression.predict(X1_test).T.flatten()

241/241 [==============================] - 1s 5ms/step


In [42]:
reg_neuro_pred

array([6510.318, 6510.318, 6510.318, ..., 6510.318, 6510.318, 6510.318],
      dtype=float32)

In [43]:
from math import sqrt

print(f'MAE: {s.MAE(y1_test, reg_neuro_pred)}')
print(f'MSE: {s.MSE(y1_test, reg_neuro_pred)}')
print(f'RMSE: {s.RMSE(y1_test, reg_neuro_pred)}')
print(f'MAPE: {sqrt(s.MAPE(y1_test, reg_neuro_pred))}')
print(f'R^2: {s.score(y1_test, reg_neuro_pred)}')

MAE: 4553.404678191801
MSE: 41256489.26332753
RMSE: 6423.121457930523
MAPE: 1.6423186093697606
R^2: 0.9995330720912234


In [44]:
model_regression.save('../models/RegressionModelWithSigmoid')

INFO:tensorflow:Assets written to: ../models/RegressionModelWithSigmoid\assets


INFO:tensorflow:Assets written to: ../models/RegressionModelWithSigmoid\assets


## Классификация

In [47]:
model_classification_2 = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(64, activation="relu", input_shape=(21,)),
        tf.keras.layers.Dense(128, activation="relu"),
        tf.keras.layers.Dropout(0.05),
        tf.keras.layers.Dense(64, activation="relu"),
        tf.keras.layers.Dense(32, activation="relu"),
        tf.keras.layers.Dense(16, activation="relu"),
        tf.keras.layers.Dense(3, activation="softmax"),
    ]
)

In [59]:
w_0, w_1, w_2 = tuple(y_train_ros.value_counts().sort_index().apply(lambda x: 1/x).values)

In [49]:
model_classification_2.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.005), loss="sparse_categorical_crossentropy")

In [61]:
model_classification_2.fit(X_train_ros, y_train_ros, epochs=25,
                           class_weight={0: w_0, 1: w_1, 2: w_2})

Epoch 1/25
13428/13428 [==============================] - 57s 4ms/step - loss: 6.7517e-06
Epoch 2/25
13428/13428 [==============================] - 41s 3ms/step - loss: 6.6593e-06
Epoch 3/25
13428/13428 [==============================] - 45s 3ms/step - loss: 6.6285e-06
Epoch 4/25
13428/13428 [==============================] - 50s 4ms/step - loss: 6.5914e-06
Epoch 5/25
13428/13428 [==============================] - 50s 4ms/step - loss: 6.5486e-06
Epoch 6/25
13428/13428 [==============================] - 73s 5ms/step - loss: 6.5018e-06
Epoch 7/25
13428/13428 [==============================] - 75s 6ms/step - loss: 6.4536e-06
Epoch 8/25
13428/13428 [==============================] - 66s 5ms/step - loss: 6.4088e-06
Epoch 9/25
13428/13428 [==============================] - 69s 5ms/step - loss: 6.3523e-06
Epoch 10/25
13428/13428 [==============================] - 66s 5ms/step - loss: 6.3002e-06
Epoch 11/25
13428/13428 [==============================] - 65s 5ms/step - loss: 6.2480e-06
Epoch 12

In [64]:
a = np.array([])

In [66]:
clf_neuro_pred = list(map(lambda x: np.argmax(x), model_classification_2.predict(X2_test)))

2617/2617 [==============================] - 5s 2ms/step


In [67]:
s.Confusion_matrix(y2_test, clf_neuro_pred)

array([[42021, 10430, 18021],
       [  396,   272,   867],
       [ 1598,  1512,  8598]])

In [69]:
s.report(y2_test, clf_neuro_pred)

Accuracy	0.6079077823568059
Precision	{0.0: 0.9546972622969442, 1.0: 0.022269526772556083, 2.0: 0.3128137961143855}
Recall		{0.0: 0.5962793733681462, 1.0: 0.1771986970684039, 2.0: 0.7343696617697301}
F1		{0.0: 0.36703730554560776, 1.0: 0.019783256964142848, 2.0: 0.21937031178241567}



In [70]:
model_classification_2.save('../models/ClassificationModel')

INFO:tensorflow:Assets written to: ../models/ClassificationModel\assets


INFO:tensorflow:Assets written to: ../models/ClassificationModel\assets


# Задание 2

In [31]:
import numdifftools as nd

In [81]:
X1_train.shape

(30824, 45)

In [48]:
try:
    imp.reload(sys.modules['algorithms'])
except KeyError:
    pass

from algorithms import NeuroNet, NeuroLayer

In [46]:
my_model = NeuroNet([
    NeuroLayer(32, 'relu'),
    NeuroLayer(16, 'relu'),
    NeuroLayer(1, 'linear')
], (45,))

In [47]:
my_model.compile(loss='mse')

In [104]:
import warnings
warnings.filterwarnings('ignore')

In [160]:
my_model.fit(X1_train, y1_train, 8, 0.05)

Initializing epoch 1 of 8
15412/15412
Initializing epoch 2 of 8
15412/15412
Initializing epoch 3 of 8
15412/15412
Initializing epoch 4 of 8
15412/15412
Initializing epoch 5 of 8
15412/15412
Initializing epoch 6 of 8
15412/15412
Initializing epoch 7 of 8
15412/15412
Initializing epoch 8 of 8
15412/15412


In [161]:
my_model.matrices

[array([[ 8.95043071e+42,  7.92112107e+40,  8.72195513e+37, ...,
         -9.10159154e-01,  1.41417680e+00,  3.96452506e+37],
        [ 2.52996113e+42,  2.23901275e+40,  2.46537940e+37, ...,
         -6.38580824e-01, -7.72623631e-01,  1.12062700e+37],
        [ 1.73554178e+43,  1.53595251e+41,  1.69123900e+38, ...,
         -6.70320201e-01, -8.22555542e-01,  7.68745001e+37],
        ...,
        [ 6.66394764e+42,  5.89758614e+40,  6.49383859e+37, ...,
         -1.25475920e+00, -9.53947036e-01,  2.95174481e+37],
        [ 1.14437475e+43,  1.01277036e+41,  1.11516256e+38, ...,
         -1.09086431e+00,  4.38833116e-01,  5.06892074e+37],
        [ 1.43500863e+43,  1.26998101e+41,  1.39837749e+38, ...,
         -1.12550935e-01, -1.02298491e+00,  6.35626133e+37]]),
 array([[ 1.97628931e+21,  5.58625087e+20,  3.83214257e+21,
          2.04776677e+21, -4.93574949e-01, -3.97911915e-01,
          9.49231043e-01,  2.49499304e+21,  1.62111180e-01,
         -1.03213854e+00,  1.58611923e-01,  2.403

In [162]:
myRes = my_model.predict(X1_test)

In [163]:
from math import sqrt

print(f'MAE: {s.MAE(y1_test, myRes)}')
print(f'MSE: {s.MSE(y1_test, myRes)}')
print(f'RMSE: {s.RMSE(y1_test, myRes)}')
print(f'MAPE: {sqrt(s.MAPE(y1_test, myRes))}')
print(f'R^2: {s.score(y1_test, myRes)}')

MAE: 3.126811972279533e+82
MSE: 1.2652477568189976e+165
RMSE: 3.557032129204061e+82
MAPE: 4.600252154318531e+39
R^2: -3.068216807517924e+157


In [49]:
try_model = NeuroNet([
    NeuroLayer(32, 'relu'),
    NeuroLayer(16, 'tanh'),
    NeuroLayer(1, 'linear')
], (45,))

In [50]:
try_model.compile(loss='mse')

In [51]:
try_model.fit(X1_train.sample(2000, random_state=42), y1_train.sample(2000, random_state=42), 6, 0.05)

Initializing epoch 1 of 6
1000/1000		Loss: 236449538.7593568
Initializing epoch 2 of 6
1000/1000		Loss: 248905389.1956655
Initializing epoch 3 of 6
1000/1000		Loss: 248905389.2096838
Initializing epoch 4 of 6
1000/1000		Loss: 248905389.2088447
Initializing epoch 5 of 6
1000/1000		Loss: 248905389.1964317
Initializing epoch 6 of 6
1000/1000		Loss: 248905389.21168295


In [52]:
pred = try_model.predict(X1_test)

In [53]:
try_model.matrices

[array([[-8.92192304e-01,  2.69976290e-01, -6.70675510e-01, ...,
          1.28534843e+00,  9.84646681e-01,  6.96738909e-01],
        [-1.13554471e+00, -1.50319292e+00,  2.51909567e+00, ...,
          1.48140180e+00, -2.49876084e+00,  8.07141219e-01],
        [ 5.47694355e+12,  2.18310970e+10,  2.40985506e+07, ...,
          2.35871400e+00, -2.49621523e-02,  5.03205876e-01],
        ...,
        [ 1.00865135e+13,  4.02048427e+10,  4.43806568e+07, ...,
          1.06615480e+00,  1.04405879e-01,  3.97558837e-01],
        [-1.11954041e+00,  4.01585674e-01, -1.16967635e-01, ...,
          3.05944575e-01, -1.56134827e+00, -1.48389365e+00],
        [ 1.83955811e+12,  7.33247863e+09,  8.09405609e+06, ...,
         -8.64740127e-01,  1.80244293e+00,  2.55079258e-01]]),
 array([[-1.21388294e+00,  3.52278027e-01, -4.31456111e-01,
          9.63845407e-01,  1.54483657e+00, -1.66256588e-01,
         -1.29161686e-02, -1.14820959e+00,  4.55430070e-01,
          7.25442769e-01, -1.74213085e+00, -7.879

In [43]:
from sklearn.metrics import r2_score

In [54]:
from math import sqrt

print(f'MAE: {s.MAE(y1_test, pred)}')
print(f'MSE: {s.MSE(y1_test, pred)}')
print(f'RMSE: {s.RMSE(y1_test, pred)}')
print(f'MAPE: {sqrt(s.MAPE(y1_test, pred))}')
print(f'R^2: {r2_score(y1_test, pred)}')

MAE: 4352.215587717735
MSE: 43595774.370496236
RMSE: 6602.709623366473
MAPE: 1.4454122580080249
R^2: -0.05719442646244666


## Попытки сделать хоть что-то

In [131]:
a0 = X_train_rus.to_numpy()[0:1].T
a0

array([[ 1.],
       [ 0.],
       [ 1.],
       [21.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 2.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [11.],
       [ 4.],
       [ 6.]])

In [94]:
w = np.random.normal(0, 1, (16, 21))
w

array([[-5.99831712e-01,  6.53706450e-01,  3.08746761e+00,
        -1.10639271e+00, -4.90758522e-01, -2.48222159e+00,
         1.02044697e+00,  5.18292088e-01,  1.98077156e+00,
        -5.56135334e-01,  1.09293410e+00, -1.73152208e-01,
         3.59635119e-01,  2.13807051e-01,  8.81914051e-01,
        -1.22658586e+00,  1.57072993e+00,  3.01633982e-01,
        -7.69820320e-02, -5.19294106e-01,  1.69735983e+00],
       [ 1.14256391e+00, -1.72041089e-01, -5.16179875e-01,
         8.67832992e-01, -1.00036505e+00, -2.15848769e+00,
         6.97197934e-01, -2.62723097e-03, -2.37791777e-02,
        -5.06660476e-01,  1.59734583e-01, -8.41940582e-01,
        -6.55453107e-02,  8.89910546e-01,  6.77571446e-01,
         2.43635252e+00, -8.47645993e-01, -2.98706901e-01,
         8.52671681e-01,  9.40719422e-02,  2.60781248e-01],
       [ 2.56648844e-01,  1.93832896e+00,  1.14230321e+00,
         4.08518220e-01, -2.00852228e+00,  7.24155154e-01,
         4.47275053e-01,  1.38530383e+00,  3.65218406e

In [23]:
def sigmoid(x: np.ndarray) -> np.ndarray:
    return 1/(1+np.exp(-1 * x))

In [24]:
def relu(x: np.ndarray) -> np.ndarray:
    return np.vectorize(lambda x: x if x > 0 else 0)(x)

In [25]:
def linear(x):
    return x

In [62]:
b1 = np.random.normal(0, 1, (16, 1))

In [27]:
import numdifftools as nd

In [132]:
a1 = relu(np.dot(w, a0) + b1)
ga1 = nd.Derivative(relu)(np.dot(w, a0) + b1)
# b = np.hstack((b, np.ones((b.shape[0], 1))))
a1

array([[ 0],
       [32],
       [ 0],
       [ 1],
       [15],
       [ 2],
       [12],
       [ 3],
       [20],
       [ 0],
       [15],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0]])

In [65]:
u = np.random.normal(0, 1, (8, 16))
u

array([[-1.00513902e+00, -1.13130816e+00,  7.46580840e-01,
        -9.02937895e-01, -5.65255653e-01, -5.91846939e-01,
         8.28447051e-01,  1.22466347e+00, -2.61002002e-01,
         1.37119459e-02, -1.36719199e+00, -3.66465856e-01,
         7.85969703e-01,  1.13226603e-01, -8.02046898e-01,
         5.69975289e-03],
       [ 1.68069827e-01,  4.55905389e-01, -2.17809337e+00,
         3.00814567e-01, -2.91929430e-01, -1.08523207e+00,
         1.54673436e-01,  1.20106479e+00,  1.42705195e+00,
        -1.02895813e+00, -1.67012371e+00, -3.97590747e-01,
        -1.11460386e+00, -3.15487414e-01,  6.09728513e-01,
        -1.14376043e-01],
       [ 2.10688270e-01, -3.63223558e-01, -1.12297953e-01,
        -2.47447364e-01,  6.12758253e-01, -5.62778409e-01,
        -3.31179449e-01, -3.83289986e-01,  6.02876807e-01,
        -2.46011406e-03,  9.09971123e-02, -2.92770331e-01,
         8.09758259e-01, -4.62214705e-01, -5.43513605e-02,
        -6.02488181e-01],
       [ 4.65103068e-01, -2.37943622e

In [66]:
b2 = np.random.normal(0, 1, (8, 1))

In [133]:

a2 = relu(np.dot(u, a1) + b2)
ga2 = nd.Derivative(relu)(np.dot(u, a1) + b2)
a2

array([[ 0],
       [17],
       [ 4],
       [24],
       [ 0],
       [11],
       [ 0],
       [61]])

In [97]:
h = np.random.normal(0, 1, (3, 8))
h

array([[-0.44750304,  0.61021447,  0.16876233, -0.64901547, -1.45910631,
        -0.39095275, -1.35904318,  2.34879791],
       [-1.39123729, -0.01546922, -2.94460834,  1.64984471,  0.06596867,
         1.42604428, -0.97928673,  1.91492589],
       [-0.09701569, -0.18186451, -2.27348294,  2.05930079, -1.82239293,
        -0.88423973, -0.10610185, -1.42790186]])

In [98]:
b3 = np.random.normal(0, 1, (3, 1))

In [36]:
def softmax(x: np.ndarray) -> np.ndarray:
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x)

In [135]:

a3 = softmax(np.dot(h, a2) + b3)
ga3 = nd.Derivative(softmax)(np.dot(h, a2) + b3)
a3

array([[8.73789646e-12],
       [1.00000000e+00],
       [1.89069089e-95]])

In [101]:
a3 = a3.flatten().tolist()

In [103]:
y2_train.values[0:1]

array([0.])

In [87]:
import numdifftools as nd

In [85]:
def MSE(yp, yr):
    return np.mean((yr-yp)**2)

In [136]:
import numpy as np

def cross_entropy(y_pred, y_true):
    """
    Рассчитывает кросс-энтропию между двумя распределениями.

    Аргументы:
    y_true -- массив NumPy, содержащий фактические метки классов
    y_pred -- массив NumPy, содержащий вероятность принадлежности каждому классу

    Возвращает:
    Значение кросс-энтропии между y_true и y_pred
    """

    # Преобразуем метки классов в one-hot-кодировку
    y_true_onehot = np.zeros(y_pred.T.shape)
    y_true_onehot[np.arange(len(y_true)), y_true] = 1

    # Рассчитываем кросс-энтропию между y_true_onehot и y_pred
    return -np.sum(np.multiply(y_true_onehot, np.log(y_pred)))


In [139]:
gr = nd.Derivative(cross_entropy)(a3, y_train_rus.values[0:1].astype(int))
gr

ValueError: fun did not return data of correct size (it must be vectorized)

In [122]:
prpr3 = np.multiply(ga3.T, np.dot(gr, 1))
prpr3

array([[ 88.42951622, 105.40508397, -40.00067704]])

In [123]:
b3

array([[-1.80424211],
       [-1.94420324],
       [-0.40995555]])

In [124]:
b3 - prpr3.T

array([[ -90.23375833],
       [-107.34928722],
       [  39.59072149]])

In [125]:
h - 0.05*np.dot(a2, prpr3).T

array([[-4.47503042e-01, -7.45548743e+01, -1.75171409e+01,
        -1.06764435e+02, -1.45910631e+00, -4.90271867e+01,
        -1.35904318e+00, -2.67361227e+02],
       [-1.39123729e+00, -8.96097906e+01, -2.40256251e+01,
        -1.24836256e+02,  6.59686669e-02, -5.65467519e+01,
        -9.79286735e-01, -3.19570580e+02],
       [-9.70156897e-02,  3.38187110e+01,  5.72665247e+00,
         5.00601132e+01, -1.82239293e+00,  2.11161326e+01,
        -1.06101847e-01,  1.20574163e+02]])

In [126]:
prpr2 = np.multiply(ga2.T, np.dot(prpr3, h))
b2 - prpr2.T

array([[ 0.69963461],
       [ 0.2437286 ],
       [ 0.36723731],
       [ 1.15929178],
       [-0.6998839 ],
       [-0.14158178],
       [-1.15045347],
       [ 1.35188175]])

In [127]:
u - 0.05*np.dot(a1, prpr2).T

array([[-1.00513902e+00, -1.13130816e+00,  7.46580840e-01,
        -9.02937895e-01, -5.65255653e-01, -5.91846939e-01,
         8.28447051e-01,  1.22466347e+00, -2.61002002e-01,
         1.37119459e-02, -1.36719199e+00, -3.66465856e-01,
         7.85969703e-01,  1.13226603e-01, -8.02046898e-01,
         5.69975289e-03],
       [ 1.68069827e-01,  4.55905389e-01, -2.17809337e+00,
         3.00814567e-01, -2.91929430e-01, -1.08523207e+00,
         1.54673436e-01,  1.20106479e+00,  1.42705195e+00,
        -1.02895813e+00, -1.67012371e+00, -3.97590747e-01,
        -1.11460386e+00, -3.15487414e-01,  6.09728513e-01,
        -1.14376043e-01],
       [ 2.10688270e-01, -3.63223558e-01, -1.12297953e-01,
        -2.47447364e-01,  6.12758253e-01, -5.62778409e-01,
        -3.31179449e-01, -3.83289986e-01,  6.02876807e-01,
        -2.46011406e-03,  9.09971123e-02, -2.92770331e-01,
         8.09758259e-01, -4.62214705e-01, -5.43513605e-02,
        -6.02488181e-01],
       [ 4.65103068e-01, -2.37943622e

In [93]:
prpr1 = np.multiply(ga1.T, np.dot(prpr2, u))
b1 - prpr1.T

array([[-0.56662508],
       [-0.3399058 ],
       [-1.32186505],
       [ 0.26539055],
       [ 0.10928864],
       [ 1.42366778],
       [-0.53659678],
       [ 0.19662963],
       [ 0.70926255],
       [ 0.7196187 ],
       [-0.84411045],
       [ 1.03775292],
       [-1.346275  ],
       [-1.12232415],
       [ 0.45442156],
       [-0.33680655]])

In [94]:
w - 0.05*np.dot(a0, prpr1).T

array([[ 1.26535697e+00, -4.40823694e-01, -8.25571055e-01,
        -2.04464790e+00, -8.69190953e-01,  2.48261358e-01,
        -2.65229101e-01,  7.82972908e-01,  1.80627599e-02,
         1.88836021e-01, -4.52474846e-01,  1.54435111e+00,
         1.20521892e+00,  1.72523662e+00, -3.46716819e-01,
        -5.35525914e-01,  6.99676629e-01,  1.51221333e+00,
        -8.95649305e-02,  1.26670754e+00, -6.49674938e-01,
         1.38068883e+00,  9.48008675e-01,  1.99795155e-01,
        -8.83774237e-01, -2.22752662e-01, -3.01182429e-01,
        -1.24657324e+00,  7.52582768e-01, -7.56288526e-01,
        -1.12836656e+00,  8.09879446e-01, -1.26996867e+00,
        -1.26146867e-01,  5.18620889e-02, -1.76753654e-01,
         9.21068463e-01, -1.45625750e-01,  1.12601625e+00,
        -9.33929921e-01,  6.66215640e-02, -1.18615329e-03,
         9.58141642e-02, -1.16905021e-02, -1.25505628e+00],
       [ 4.28670874e-01, -1.69377193e+00, -1.01096199e-01,
        -1.01622135e+00, -1.66643464e+00, -1.93214431e+

In [74]:
import tensorflow as tf

In [91]:
scce = tf.keras.losses.SparseCategoricalCrossentropy()