In [1]:
import pandas as pd
import numpy as np
import importlib as imp
import sys
sys.path.insert(0,'..\src')

In [2]:
data = pd.read_csv("../data/spam (1).csv", encoding='cp1252')
data

v1                                                 v2 Unnamed: 2   
0      ham  Go until jurong point, crazy.. Available only ...        NaN  \
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [3]:
data.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis=1, inplace=True)
data

v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [4]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [5]:
my_stopwords = nlp.Defaults.stop_words

res = data['v2'].copy()

for ind, text in enumerate(data['v2'].values):
    doc = nlp(text)
    filterred = [i for i in doc if i.lower_ not in my_stopwords and not i.is_punct]
    lem = [i.lemma_ for i in filterred]
    res.iloc[ind] = ' '.join(lem)
    
data['v2'] = res
data

v1                                                 v2
0      ham  jurong point crazy available bugis n great wor...
1      ham                              ok lar joke wif u oni
2     spam  free entry 2 wkly comp win FA Cup final tkts 2...
3      ham                                u dun early hor u c
4      ham                              nah think go usf live
...    ...                                                ...
5567  spam  2nd time try 2 contact u. U win å£750 Pound pr...
5568   ham                           Ì b go esplanade fr home
5569   ham                               pity mood suggestion
5570   ham  guy bitching act like interested buy week give...
5571   ham                                          rofl true

[5572 rows x 2 columns]

In [34]:
count_vectorizer = CountVectorizer()

bow = count_vectorizer.fit_transform(data['v2'].values)
bow.shape

(5572, 7729)

In [6]:
try:
    imp.reload(sys.modules['algorithms'])
except KeyError:
    pass

from algorithms import BagOfWords as bagger

In [7]:
cv = bagger()

bow = cv.fit_transform(data['v2'].values)
bow.shape

(5572, 9409)

In [9]:
from sklearn.feature_selection import VarianceThreshold

In [8]:
from sklearn.decomposition import PCA

In [13]:
pca = PCA(n_components=28)
X_pca = pca.fit_transform(bow)
print(X_pca.shape)

(5572, 28)


In [14]:
try:
    imp.reload(sys.modules['algorithms'])
except KeyError:
    pass

from algorithms import PCA as mypcalol

In [15]:
my_pca = mypcalol(n=1000)
mXp = my_pca.fit_transform(bow)
mXp.shape

(5572, 1000)

In [16]:
import importlib as imp

try:
    imp.reload(sys.modules['algorithms'])
except KeyError:
    pass

from algorithms import kNN

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(mXp, data['v1'].values, test_size=0.2)

In [18]:
mykNN = kNN(X_train, y_train, 5)

In [19]:
my_pred = mykNN.predict(X_test)

In [20]:
my_pred

array(['spam', 'spam', 'spam', ..., 'spam', 'spam', 'spam'], dtype='<U4')

In [21]:
try:
    imp.reload(sys.modules['Scoring'])
except KeyError:
    pass

from Scoring import Scoring

s = Scoring()

In [28]:
list(np.unique(y_train).flatten())

['ham', 'spam']

In [22]:
s.Confusion_matrix(y_test, my_pred)

array([[  0, 975],
       [ 50,  90]])

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_pca, data['v1'].values, test_size=0.2)
mykNN = kNN(X_train, y_train, 5)
my_pred = mykNN.predict(X_test)
my_pred

array(['spam', 'spam', 'spam', ..., 'spam', 'spam', 'spam'], dtype='<U4')

In [24]:
s.Confusion_matrix(y_test, my_pred)

array([[  7, 946],
       [122,  40]])

In [25]:
try:
    imp.reload(sys.modules['algorithms'])
except KeyError:
    pass

from algorithms import NaiveBayes

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(mXp, data['v1'].values, test_size=0.2)

In [34]:
try:
    imp.reload(sys.modules['algorithms'])
except KeyError:
    pass

from algorithms import tfidf

In [35]:
tfidf_vectorizer = tfidf()
t = tfidf_vectorizer.fit_transform(data['v2'].values)
t.shape

(5572, 9409)

In [15]:
my_pca = mypcalol(n=500)
mXp = my_pca.fit_transform(t)
mXp

In [36]:
from sklearn.decomposition import PCA
pca = PCA(n_components=500)
X_pca = pca.fit_transform(t)
print(X_pca.shape)

(5572, 500)


In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_pca, data['v1'].values, test_size=0.2)
mykNN = kNN(X_train, y_train, 5)
my_pred = mykNN.predict(X_test)
my_pred

array(['spam', 'ham', 'spam', ..., 'ham', 'spam', 'spam'], dtype='<U4')

In [12]:
s.Confusion_matrix(y_test, my_pred)

array([[ 25, 932],
       [129,  29]])

In [13]:
from sklearn.decomposition import LatentDirichletAllocation

In [14]:
def print_top_words(model, feature_names, n_top_words):
    for topic_idx, topic in enumerate(model.components_):
        print("Topic #%d:" % topic_idx)
        print(" ".join([feature_names[i]
                        for i in topic.argsort()[:-n_top_words - 1:-1]]))

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

tf_vectorizer = CountVectorizer(max_df=0.5, min_df=5,
                                max_features=1000,
                                stop_words='english')
tf = tf_vectorizer.fit_transform(data['v2'])

In [20]:
lda = LatentDirichletAllocation(n_components=15, max_iter=20, 
                                learning_method='online',
                                learning_offset=50.,
                                random_state=0).fit(tf)

In [21]:
lda.components_.shape

(15, 1000)

In [22]:
lda.transform(tf).shape

(5572, 15)

In [23]:
print_top_words(lda, tf_vectorizer.get_feature_names_out(), 15)

Topic #0:
just know let ve live money really need make bed play actually fuck start drop
Topic #1:
buy guy car bring drive yo okay test mind food mum neva 30 tomo gal
Topic #2:
come love want tell need miss today friend dear message day life send pls time
Topic #3:
ur send msg minute problem aight away haha chat 150p row awesome auction goin family
Topic #4:
gt lt sorry later min pay account sir point send mail til meeting decimal today
Topic #5:
think thing work yeah amp happy lol say class lunch wish day room remember pa
Topic #6:
ok da hi say oh home right happen babe nice ready wanna pic luv xxx
Topic #7:
ask leave make feel house bit long tell watch sit face change dinner thanx bus
Topic #8:
good day time hope night hey great meet sleep morning way tomorrow think make fine
Topic #9:
free text txt new mobile ur reply tone week win nokia www uk phone just
Topic #10:
like smile pls hurt sound speak pain treat crazy open friday pretty support ass joy
Topic #11:
use tonight hour yup bo